version: '3.9'


services:
  db:
    image: postgres:13-alpine
    container_name: project-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dprjdb
  
volumes:
  postgres_data:
